// Manifest of pages the build script assembles from src/partials + src/pages.
// outputDir '.' means the page is written to the site root (index.html); other
// values are subdirectories, matching the site's existing URL structure.
module.exports = [
  {
    slug: "index",
    title: "aip Seguros y Fianzas",
    canonical: "index.html",
    bodyClass: "home wp-singular page-template-default page page-id-4176 wp-theme-tractor tractor mobile post-type-page header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "content-index",
    articleClass: "page type-page status-publish hentry",
    contentFile: "index.html",
    outputDir: ".",
    titleBar: "",
  },
  {
    slug: "conocenos",
    title: "Conócenos – aip Seguros y Fianzas",
    canonical: "conocenos/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4311 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4311",
    articleClass: "post-4311 page type-page status-publish hentry",
    contentFile: "conocenos.html",
    outputDir: "conocenos",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-05\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\t \t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs"],
  },
  {
    slug: "contacto",
    title: "Contacto – aip Seguros y Fianzas",
    canonical: "contacto/index.html",
    bodyClass: "wp-singular page-template-default page page-id-1083 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-1083",
    articleClass: "post-1083 page type-page status-publish hentry",
    contentFile: "contacto.html",
    outputDir: "contacto",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tContacto\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "aip-plus",
    title: "AIP + PLUS – aip Seguros y Fianzas",
    canonical: "aip-plus/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4564 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4564",
    articleClass: "post-4564 page type-page status-publish hentry",
    contentFile: "aip-plus.html",
    outputDir: "aip-plus",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tAIP + PLUS\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs", "roundChart"],
  },
  {
    slug: "gastos-medicos",
    title: "Gastos Médicos – aip Seguros y Fianzas",
    canonical: "gastos-medicos/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4407 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4407",
    articleClass: "post-4407 page type-page status-publish hentry",
    contentFile: "gastos-medicos.html",
    outputDir: "gastos-medicos",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tGastos Médicos\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs"],
  },
  {
    slug: "seguro-de-autos",
    title: "Seguro de Autos – aip Seguros y Fianzas",
    canonical: "seguro-de-autos/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4383 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4383",
    articleClass: "post-4383 page type-page status-publish hentry",
    contentFile: "seguro-de-autos.html",
    outputDir: "seguro-de-autos",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro de Autos\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs"],
  },
  {
    slug: "seguro-empresarial",
    title: "Seguro Empresarial – aip Seguros y Fianzas",
    canonical: "seguro-empresarial/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4446 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4446",
    articleClass: "post-4446 page type-page status-publish hentry",
    contentFile: "seguro-empresarial.html",
    outputDir: "seguro-empresarial",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro Empresarial\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs"],
  },
  {
    slug: "seguro-para-motocicletas",
    title: "Seguro para Motocicletas – aip Seguros y Fianzas",
    canonical: "seguro-para-motocicletas/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4460 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4460",
    articleClass: "post-4460 page type-page status-publish hentry",
    contentFile: "seguro-para-motocicletas.html",
    outputDir: "seguro-para-motocicletas",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro para Motocicletas\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
    vcComponents: ["tabs"],
  },
  {
    slug: "aviso-de-privacidad",
    title: "Aviso de Privacidad – aip Seguros y Fianzas",
    canonical: "aviso-de-privacidad/index.html",
    bodyClass: "wp-singular page-template-default page page-id-4135 wp-theme-tractor tractor desktop desktop-menu post-type-page page-has-animation header-sticky header-sticky-both wide page-has-no-sidebar wpb-js-composer js-comp-ver-8.5 vc_responsive",
    articleId: "post-4135",
    articleClass: "post-4135 page type-page status-publish hentry",
    contentFile: "aviso-de-privacidad.html",
    outputDir: "aviso-de-privacidad",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tAviso de Privacidad\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "seguro-de-vida",
    title: "Seguro de Vida – aip Seguros y Fianzas",
    canonical: "seguro-de-vida/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-seguro-de-vida",
    articleClass: "page type-page status-publish hentry",
    contentFile: "seguro-de-vida.html",
    outputDir: "seguro-de-vida",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro de Vida\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "hombre-clave",
    title: "Hombre Clave – aip Seguros y Fianzas",
    canonical: "hombre-clave/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-hombre-clave",
    articleClass: "page type-page status-publish hentry",
    contentFile: "hombre-clave.html",
    outputDir: "hombre-clave",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tHombre Clave\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "fianzas",
    title: "Fianzas – aip Seguros y Fianzas",
    canonical: "fianzas/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-fianzas",
    articleClass: "page type-page status-publish hentry",
    contentFile: "fianzas.html",
    outputDir: "fianzas",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tFianzas\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "rc-silla",
    title: "RC Silla – aip Seguros y Fianzas",
    canonical: "rc-silla/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-rc-silla",
    articleClass: "page type-page status-publish hentry",
    contentFile: "rc-silla.html",
    outputDir: "rc-silla",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tRC Silla\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "responsabilidad-civil",
    title: "Responsabilidad Civil – aip Seguros y Fianzas",
    canonical: "responsabilidad-civil/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-responsabilidad-civil",
    articleClass: "page type-page status-publish hentry",
    contentFile: "responsabilidad-civil.html",
    outputDir: "responsabilidad-civil",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tResponsabilidad Civil\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "seguro-de-casa-habitacion",
    title: "Seguro de Casa Habitación – aip Seguros y Fianzas",
    canonical: "seguro-de-casa-habitacion/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-seguro-de-casa-habitacion",
    articleClass: "page type-page status-publish hentry",
    contentFile: "seguro-de-casa-habitacion.html",
    outputDir: "seguro-de-casa-habitacion",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro de Casa Habitación\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "seguro-para-flotillas",
    title: "Seguro para Flotillas – aip Seguros y Fianzas",
    canonical: "seguro-para-flotillas/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-seguro-para-flotillas",
    articleClass: "page type-page status-publish hentry",
    contentFile: "seguro-para-flotillas.html",
    outputDir: "seguro-para-flotillas",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro para Flotillas\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "seguro-para-mascotas",
    title: "Seguro para Mascotas – aip Seguros y Fianzas",
    canonical: "seguro-para-mascotas/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-seguro-para-mascotas",
    articleClass: "page type-page status-publish hentry",
    contentFile: "seguro-para-mascotas.html",
    outputDir: "seguro-para-mascotas",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tSeguro para Mascotas\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
  {
    slug: "declaracion-de-cookies",
    title: "Declaración de Cookies – aip Seguros y Fianzas",
    canonical: "declaracion-de-cookies/index.html",
    bodyClass: "page-template-default page wp-theme-tractor tractor desktop desktop-menu post-type-page header-sticky header-sticky-both wide page-has-no-sidebar",
    articleId: "content-declaracion-de-cookies",
    articleClass: "page type-page status-publish hentry",
    contentFile: "declaracion-de-cookies.html",
    outputDir: "declaracion-de-cookies",
    titleBar: "<div id=\"page-title-bar\" class=\"page-title-bar page-title-bar-06\">\n\t<div class=\"page-title-bar-overlay\"></div>\n\n\t<div class=\"page-title-bar-inner\">\n\t\t<div class=\"container\">\n\t\t\t<div class=\"row row-xs-center\">\n\t\t\t\t<div class=\"col-md-12\">\n\t\t\t\t\t\t\t<div class=\"page-title-bar-heading\">\n\t\t\t<h1 class=\"heading\">\n\t\t\t\tDeclaración de Cookies\t\t\t</h1>\n\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t\t</div>\n</div>",
  },
];
